# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-02 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('8full', '마감'), ('1normal', '일반'), ('7canceled', '취소'), ('6deleted', '삭제됨'), ('5hidden', '관리자 삭제')], default='1normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='teamreply',
            name='reply_to',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='teamreply',
            name='status',
            field=models.CharField(choices=[('1normal', '일반'), ('6deleted', '삭제됨'), ('5hidden', '관리자 삭제')], default='1normal', max_length=10),
        ),
    ]
