# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-02 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('2progress', '결재중'), ('5completed', '결재완료'), ('4canceled', '취소'), ('3rejected', '반려'), ('1proposed', '기안')], default='1proposed', max_length=12),
        ),
    ]
