# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-02 03:24
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_alarm_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alarm_list',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bookmarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ip_list',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='portrait/%Y-%m-%d/', validators=[accounts.models.img_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='scrap',
            field=models.TextField(blank=True, default=''),
        ),
    ]
