# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-02 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='category',
            field=models.CharField(choices=[('account', '계좌'), ('card', '카드'), ('membership', '멤버십'), ('other', '기타')], default='account', max_length=12),
        ),
        migrations.AlterField(
            model_name='vault',
            name='image',
            field=models.ImageField(blank=True, upload_to='vaults/'),
        ),
    ]
