# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-02 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='recipient_status',
            field=models.CharField(choices=[('1normal', '일반'), ('6deleted', '삭제됨'), ('5hidden', '관리자 삭제'), ('2read', '읽음')], default='1normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='msg',
            name='sender_status',
            field=models.CharField(choices=[('1normal', '일반'), ('6deleted', '삭제됨'), ('5hidden', '관리자 삭제'), ('2read', '읽음')], default='1normal', max_length=10),
        ),
    ]
